version: "3.9"

services:
  users-api:
    container_name: users-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - store_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-api.rule=Host(`${DOMAIN}`)"  # ← CAMBIADO: subdomain
      - "traefik.http.routers.users-api.entrypoints=websecure"
      - "traefik.http.routers.users-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.users-api.loadbalancer.server.port=${PORT}"
      - "raefik.http.services.api-admin.loadbalancer.server.port=5000"
      - "traefik.http.routers.users-api.middlewares=security-headers,ratelimit"  # ← REMOVIDO: stripprefix
      # REMOVIDO: "traefik.http.middlewares.users-api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.docker.network=store_network"

networks:
  store_network:
    external: true
